# Generated by Django 3.0.2 on 2021-05-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_books', models.BooleanField(default=False)),
                ('books_school', models.BooleanField(default=False)),
                ('books_college', models.BooleanField(default=False)),
                ('books_engineering', models.BooleanField(default=False)),
                ('books_medical', models.BooleanField(default=False)),
                ('biographic', models.BooleanField(default=False)),
                ('adventure', models.BooleanField(default=False)),
                ('childern', models.BooleanField(default=False)),
                ('cook', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('kids', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('bestseller', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('InStock', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('dec', models.CharField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('bookfront_cover', models.ImageField(default='picc', upload_to='pics')),
                ('bookback_cover', models.ImageField(default='picc', upload_to='pics')),
                ('index_1', models.ImageField(default='picc', upload_to='pics')),
                ('index_2', models.ImageField(default='picc', upload_to='pics')),
                ('index_3', models.ImageField(default='picc', upload_to='pics')),
                ('index_4', models.ImageField(default='picc', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='school_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model_name', models.CharField(default='noel', max_length=50)),
                ('school_image', models.ImageField(default='picc', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='school_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=50)),
                ('pattern', models.CharField(max_length=50)),
                ('book_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_for_school', to='home.books')),
                ('school_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='home.school_list')),
            ],
        ),
    ]
