# Generated by Django 3.0.2 on 2020-09-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_auto_20200815_1613'),
        ('accounts', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books123', to='home.books')),
            ],
        ),
    ]
