# Generated by Django 3.0.2 on 2020-09-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
