# Generated by Django 3.0.2 on 2021-05-18 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('feeback_title', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maink', to=settings.AUTH_USER_MODEL)),
                ('feebdack_book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_product', to='home.books')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main', to=settings.AUTH_USER_MODEL)),
                ('question_book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_product', to='home.books')),
            ],
        ),
        migrations.CreateModel(
            name='question_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_reply', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replydfdq', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qudfdfestion', to='feedback_questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_reply', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replyxx', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbadfdfck', to='feedback_questions.feedback')),
            ],
        ),
    ]
