# Generated by Django 3.0.2 on 2020-09-21 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='placeorder_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mobilenumber', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('address_full', models.CharField(max_length=200)),
                ('landamrk', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_product', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_which_user_buy', to='coupons.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='placedorder_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_buyer', to=settings.AUTH_USER_MODEL)),
                ('placedorder_book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_who_buy_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
