# Generated by Django 3.0.2 on 2020-09-27 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_address_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mobilenumber', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('address_full', models.CharField(max_length=200)),
                ('landamrk', models.CharField(max_length=200)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='placeorder_detail',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='placeorder_detail',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='placedorder_book',
        ),
        migrations.DeleteModel(
            name='placeorder_detail',
        ),
    ]
