# Generated by Django 3.0.2 on 2020-09-27 19:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_auto_20200928_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='placedorder_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oreder_status', models.IntegerField()),
                ('date_time', models.DateTimeField(verbose_name=datetime.timezone)),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_pointer', to='checkout.user_address_detail')),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_buyer', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_which_user_buy', to='coupons.coupon')),
                ('placedorder_book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_who_buy_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
