# Generated by Django 3.0.2 on 2020-09-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_placedorder_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder_book',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
