# Generated by Django 3.0.2 on 2020-09-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200928_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placedorder_book',
            old_name='oreder_status',
            new_name='order_status',
        ),
    ]
