# Generated by Django 3.0.2 on 2020-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200928_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address_detail',
            name='addresstype',
            field=models.CharField(default='Home', max_length=200),
        ),
    ]
