# Generated by Django 3.0.2 on 2020-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200805_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Bestselling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='Trending',
            field=models.BooleanField(default=False),
        ),
    ]
