# Generated by Django 3.0.2 on 2020-08-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200812_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Bestselling',
            new_name='bestselling',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='Trending',
            new_name='trending',
        ),
    ]
