# Generated by Django 3.0.2 on 2021-05-18 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='placedorder_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('1', 'order is open'), ('2', 'order is accepted'), ('3', 'order packing'), ('4', 'out for delivery'), ('5', 'delivered'), ('6', 'order cancled'), ('7', 'complaint raise'), ('8', 'raise return'), ('9', 'return in progress'), ('10', 'return accepted'), ('11', 'return pickedup'), ('12', 'return order recevied'), ('13', 'return product quality check in progress'), ('14', 'return payment in progress'), ('15', 'return payment complete')], default='order is open', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('date_time', models.DateTimeField()),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_pointerdfdfd', to='checkout.user_address_detail')),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_buyerdfdfd', to=settings.AUTH_USER_MODEL)),
                ('coupon', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books_which_user_buydfdf', to='checkout.coupon_here')),
                ('placedorder_book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_who_buy_bookdfdf', to='home.books')),
            ],
        ),
    ]
