# Generated by Django 3.0.2 on 2021-06-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('myorders', '0005_auto_20210601_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder_book',
            name='coupon',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_which_user_buydfdf', to='checkout.coupon_here'),
        ),
        migrations.AlterField(
            model_name='placedorder_book',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'order cancled'), (2, 'complaint raise'), (3, 'raise return'), (4, 'return in progress'), (5, 'return accepted'), (6, 'return pickedup'), (7, 'return order recevied'), (8, 'return product quality check in progress'), (9, 'return payment in progress'), (10, 'return payment complete'), (11, 'order is placed'), (12, 'order is accepted'), (13, 'order packing'), (14, 'out for delivery'), (15, 'delivered')], default='order is open'),
        ),
    ]
