diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
add.interactive.usebuiltin=true
pull.rebase=false
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
user.name=pratikgosavii
user.email=pratikgosavi654@gmail.com
http.sslbackend=openssl
http.sslcainfo=C:\Program Files\Git\mingw64\ssl\cert.pem
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/pratikgosavii/boho
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
credential.username='pratikgosavii
