# Generated by Django 3.0.2 on 2021-07-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
